logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.cors: TRACE
    org.springframework.web.cors: TRACE

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/exemplo
    username: postgres
    password: masterkey
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Cuidado com esta configuração em produção!
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /api